name: Deploy to Azure

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify your Node.js version

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Move frontend build to backend public folder
        run: mv ./frontend/dist ./backend

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ''  # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Add your Azure publish profile secret
          package: ./backend  # Path to the backend directory to deploy
